### Limpieza conjunta

In [2]:
#IMPORTANDO LIBRERIAS NECESARIAS
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [7]:
df_limpio = pd.read_csv("hr_raw_data.csv", index_col=0)
df_limpio.head()

age attrition businesstravel    dailyrate                department  \
0  51        No            NaN  2015.722222                       NaN   
1  52        No            NaN  2063.388889                       NaN   
2  42        No  travel_rarely  1984.253968   Research & Development    
3  47        No  travel_rarely  1771.404762                       NaN   
4  46        No            NaN  1582.771346                       NaN   

   distancefromhome  education    educationfield  employeecount  \
0                 6          3               NaN              1   
1                 1          4     Life Sciences              1   
2                 4          2  Technical Degree              1   
3                 2          4           Medical              1   
4                 3          3  Technical Degree              1   

   employeenumber  environmentsatisfaction  gender  hourlyrate  \
0               1                        1       0         NaN   
1               2                        3       0         NaN   
2               3                        3       0         NaN   
3               4                        1       1         NaN   
4               5                        1       1         NaN   

   jobinvolvement  joblevel              jobrole  jobsatisfaction  \
0               3         5   resEArch DIREcToR                 3   
1               2         5             ManAGeR                 3   
2               3         5             ManaGER                 4   
3               3         4   ReseArCH DIrECtOr                 3   
4               4         4     sAleS EXECUtIve                 1   

  maritalstatus monthlyincome monthlyrate  numcompaniesworked over18 overtime  \
0           NaN     16280,83$   42330,17$                   7      Y       No   
1           NaN           NaN   43331,17$                   0    NaN      NaN   
2       Married           NaN   41669,33$                   1    NaN       No   
3       Married     14307,50$   37199,50$                   3      Y      NaN   
4      Divorced     12783,92$   33238,20$                   2      Y       No   

   percentsalaryhike performancerating  relationshipsatisfaction  \
0                 13               3,0                         3   
1                 14               3,0                         1   
2                 11               3,0                         4   
3                 19               3,0                         2   
4                 12               3,0                         4   

  standardhours  stockoptionlevel totalworkingyears  trainingtimeslastyear  \
0     Full Time                 0               NaN                      5   
1           NaN                 1              34,0                      5   
2           NaN                 0              22,0                      3   
3     Full Time                 2               NaN                      2   
4           NaN                 1               NaN                      5   

  worklifebalance  yearsatcompany yearsincurrentrole  yearssincelastpromotion  \
0             3,0              20                NaN                       15   
1             3,0              33                NaN                       11   
2             NaN              22                NaN                       11   
3             NaN              20                NaN                        5   
4             3,0              19                NaN                        2   

   yearswithcurrmanager sameasmonthlyincome  datebirth      salary  \
0                    15           16280,83$       1972  195370,00$   
1                     9                 NaN       1971  199990,00$   
2                    15                 NaN       1981  192320,00$   
3                     6           14307,50$       1976  171690,00$   
4                     8           12783,92$       1977         NaN   

                        roledepartament  numberchildren remotework  
0     

### Columnas Gabi

In [ ]:
#Vamos a limpiar la columna age
df_limpio['age'] = df_limpio['age'].str.strip().str.lower()

In [9]:
def convertir_a_numero(valor):
    try:
        return int(valor)
    except ValueError: # tengo que aplicar defensiva para que los que no pueda cambiar porque estan ok no me de error
        try:
            return w2n.word_to_num(valor)
        except:
            return None

In [10]:
df_limpio['age'] = df_limpio['age'].apply(convertir_a_numero)

In [11]:
df_limpio["age"].unique()

array([51., 52., 42., 47., 46., 48., 59., 41., 56., 38., 55., 40., 58.,
       35., 45., 33., 36., 34., nan, 53., 43., 60., 32., 37., 49., 39.,
       50., 44., 30., 29., 31., 54., 57., 27., 28., 26., 25., 24., 23.,
       22., 21., 20., 19., 18.])

In [12]:
df_limpio["distancefromhome"].unique()

array([  6,   1,   4,   2,   3,  22,  25,   9,   7,  23,  10,  12,  14,
       -13,  15,   8, -42,  28, -37,   5,  16, -35,  26, -26,  24,  29,
       -25,  17,  21, -18, -10, -30, -27,  20, -31, -29, -39,  18, -21,
       -15,  11,  13, -14,  19, -33, -34, -46, -36, -19,  27, -12, -23,
       -45, -28, -47, -32, -24, -16, -22, -41, -49, -11, -48, -38, -20,
       -17, -43, -40, -44])

In [19]:
df_limpio["distancefromhome"] = df_limpio["distancefromhome"].abs()

In [22]:
df_limpio["distancefromhome"].unique()

array([ 6,  1,  4,  2,  3, 22, 25,  9,  7, 23, 10, 12, 14, 13, 15,  8, 42,
       28, 37,  5, 16, 35, 26, 24, 29, 17, 21, 18, 30, 27, 20, 31, 39, 11,
       19, 33, 34, 46, 36, 45, 47, 32, 41, 49, 48, 38, 43, 40, 44])

In [23]:
df_limpio.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeecount',
       'employeenumber', 'environmentsatisfaction', 'gender', 'hourlyrate',
       'jobinvolvement', 'joblevel', 'jobrole', 'jobsatisfaction',
       'maritalstatus', 'monthlyincome', 'monthlyrate', 'numcompaniesworked',
       'over18', 'overtime', 'percentsalaryhike', 'performancerating',
       'relationshipsatisfaction', 'standardhours', 'stockoptionlevel',
       'totalworkingyears', 'trainingtimeslastyear', 'worklifebalance',
       'yearsatcompany', 'yearsincurrentrole', 'yearssincelastpromotion',
       'yearswithcurrmanager', 'sameasmonthlyincome', 'datebirth', 'salary',
       'roledepartament', 'numberchildren', 'remotework'],
      dtype='object')

In [ ]:
# Quitamos employeecount porque el valor es 1 y no aporta información
df_limpio = df_limpio.drop(columns=["employeecount"])

In [ ]:
df_limpio.columns #comprobamos que ya no está

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'hourlyrate', 'jobinvolvement',
       'joblevel', 'jobrole', 'jobsatisfaction', 'maritalstatus',
       'monthlyincome', 'monthlyrate', 'numcompaniesworked', 'over18',
       'overtime', 'percentsalaryhike', 'performancerating',
       'relationshipsatisfaction', 'standardhours', 'stockoptionlevel',
       'totalworkingyears', 'trainingtimeslastyear', 'worklifebalance',
       'yearsatcompany', 'yearsincurrentrole', 'yearssincelastpromotion',
       'yearswithcurrmanager', 'sameasmonthlyincome', 'datebirth', 'salary',
       'roledepartament', 'numberchildren', 'remotework'],
      dtype='object')

### Columnas Irene

In [27]:
'''¿borramos hourlyrate?'''

'¿borramos hourlyrate?'

In [ ]:
def minusculas(celda): #quitemos las mayúculas a jobrole
  try:
    return celda.lower()
  except:
    return celda

In [29]:
df_limpio['jobrole'] = df_limpio['jobrole'].apply(minusculas)

In [31]:
df_limpio['jobrole'] = df_limpio['jobrole'].str.strip()

In [32]:
df_limpio['jobrole'].unique()

array(['research director', 'manager', 'sales executive',
       'manufacturing director', 'research scientist',
       'healthcare representative', 'laboratory technician',
       'sales representative', 'human resources'], dtype=object)

In [33]:
df_limpio['maritalstatus'] = df_limpio['maritalstatus'].apply(minusculas)

In [35]:
df_limpio['maritalstatus'] = df_limpio['maritalstatus'].replace('marreid', 'married')

In [36]:
df_limpio['maritalstatus'].unique() #aplicamos minúsculas

array([nan, 'married', 'divorced', 'single'], dtype=object)

In [37]:
df_limpio['gender'].replace({0: 'Male', 1: 'Female'}, inplace=True)

/tmp/ipykernel_1334870/2639878342.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_limpio['gender'].replace({0: 'Male', 1: 'Female'}, inplace=True)


In [38]:
df_limpio['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [39]:
df_limpio['environmentsatisfaction'] = np.where(
  df_limpio['environmentsatisfaction'].between(10, 49), # Valores de 2 dígitos
  df_limpio['environmentsatisfaction'] // 10,      # División entera (primer dígito)
  df_limpio['environmentsatisfaction']         # Valores 1-4 se mantienen
)

In [40]:
df_limpio['environmentsatisfaction'].unique()

array([1, 3, 4, 2])

In [41]:
df_limpio['environmentsatisfaction'].value_counts()

environmentsatisfaction
4    509
3    490
1    341
2    338
Name: count, dtype: int64

In [42]:
df_limpio['monthlyincome'] = df_limpio['monthlyincome'].str.replace('$', '', regex=False).str.replace(',', '.', regex=False).astype(float)

In [43]:

df_limpio.rename(columns= {'monthlyincome': 'monthlyincome_$'}, inplace=True)

In [44]:
df_limpio['monthlyrate'] = df_limpio['monthlyrate'].str.replace('$', '', regex=False).str.replace(',', '.', regex=False).astype(float)

In [45]:
df_limpio.rename(columns= {'monthlyrate':'monthlyrate_$'}, inplace=True)

In [51]:
df_limpio.drop(columns=["hourlyrate"], inplace=True)

In [52]:
df_limpio.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1678 entries, 0 to 1677
Data columns (total 39 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       1665 non-null   float64
 1   attrition                 1678 non-null   object 
 2   businesstravel            877 non-null    object 
 3   dailyrate                 1678 non-null   float64
 4   department                312 non-null    object 
 5   distancefromhome          1678 non-null   int64  
 6   education                 1678 non-null   int64  
 7   educationfield            904 non-null    object 
 8   employeenumber            1678 non-null   int64  
 9   environmentsatisfaction   1678 non-null   int64  
 10  gender                    1678 non-null   object 
 11  jobinvolvement            1678 non-null   int64  
 12  joblevel                  1678 non-null   int64  
 13  jobrole                   1678 non-null   object 
 14  jobsatisfacti

Columnas Ana

In [53]:
# borrar la columna 'over 18' ('redundante')
df_limpio.drop(columns=["over18"], inplace=True)

In [54]:
# borrar la columna 'totalworkingyears' (ya existe 'yearsatacompany')
df_limpio.drop(columns=["totalworkingyears"], inplace=True)

In [55]:
# 'worklifebalance' cambiar de objeto a numeric  
df_limpio["worklifebalance"] = pd.to_numeric(df_limpio["worklifebalance"], errors="coerce")

In [56]:
# 'performancerating' cambiar de objeto a numeric  
df_limpio["performancerating"] = pd.to_numeric(df_limpio["performancerating"], errors="coerce")

In [57]:
# gestion nulos de 'standardhours' 
df_limpio['standardhours'] = df_limpio['standardhours'].fillna("Unknown")

In [58]:
# gestion nulos de 'overtime'
df_limpio['overtime'] = df_limpio['overtime'].fillna("Unknown")

In [59]:
df_limpio.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1678 entries, 0 to 1677
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       1665 non-null   float64
 1   attrition                 1678 non-null   object 
 2   businesstravel            877 non-null    object 
 3   dailyrate                 1678 non-null   float64
 4   department                312 non-null    object 
 5   distancefromhome          1678 non-null   int64  
 6   education                 1678 non-null   int64  
 7   educationfield            904 non-null    object 
 8   employeenumber            1678 non-null   int64  
 9   environmentsatisfaction   1678 non-null   int64  
 10  gender                    1678 non-null   object 
 11  jobinvolvement            1678 non-null   int64  
 12  joblevel                  1678 non-null   int64  
 13  jobrole                   1678 non-null   object 
 14  jobsatisfacti

Columnas Carmen

In [60]:
if 'numberchildren' in df_limpio.columns:
    df_limpio.drop('numberchildren', axis=1, inplace=True)
    print("'numberchildren' ha sido eliminada.")
else:
    print("'numberchildren' no se encontró en el DataFrame.")

'numberchildren' ha sido eliminada.


In [61]:
df_limpio.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeenumber',
       'environmentsatisfaction', 'gender', 'jobinvolvement', 'joblevel',
       'jobrole', 'jobsatisfaction', 'maritalstatus', 'monthlyincome_$',
       'monthlyrate_$', 'numcompaniesworked', 'overtime', 'percentsalaryhike',
       'performancerating', 'relationshipsatisfaction', 'standardhours',
       'stockoptionlevel', 'trainingtimeslastyear', 'worklifebalance',
       'yearsatcompany', 'yearsincurrentrole', 'yearssincelastpromotion',
       'yearswithcurrmanager', 'sameasmonthlyincome', 'datebirth', 'salary',
       'roledepartament', 'remotework'],
      dtype='object')

In [62]:
print("\nLimpiando 'yearsincurrentrole'...")
df_limpio['yearsincurrentrole'] = df_limpio['yearsincurrentrole'].str.replace(',', '.', regex=False).astype(float)
print("'yearsincurrentrole' convertida a tipo numérico (float).")


Limpiando 'yearsincurrentrole'...
'yearsincurrentrole' convertida a tipo numérico (float).


In [65]:
df_limpio['salary'] = df_limpio['salary'].str.replace('$', '', regex=False).str.replace(',', '.', regex=False).astype(float)

In [67]:
salario = df_limpio['sameasmonthlyincome']==df_limpio['monthlyincome']

KeyError: 'monthlyincome'